In [2]:
import re
import numpy as np
import pandas as pd
from textblob import TextBlob

ModuleNotFoundError: No module named 'textblob'

In [3]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\c_fre\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [4]:
from IPython.display import display, clear_output
pd.set_option('display.max_columns', 10000)
pd.set_option('display.max_rows', 10000)

In [5]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [9]:
initial_csv = pd.read_csv('tweets.csv')
initial_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10004 entries, 0 to 10003
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               10004 non-null  int64
 1   conversation_id  10004 non-null  int64
 2   created_at       10004 non-null  object
 3   date             10004 non-null  object
 4   time             10004 non-null  object
 5   timezone         10004 non-null  int64
 6   user_id          10004 non-null  int64
 7   username         10004 non-null  object
 8   name             10004 non-null  object
 9   place            7 non-null      object
 10  tweet            10004 non-null  object
 11  language         10004 non-null  object
 12  mentions         10004 non-null  object
 13  urls             10004 non-null  object
 14  photos           10004 non-null  object
 15  replies_count    10004 non-null  int64
 16  retweets_count   10004 non-null  int64
 17  likes_count      10004 non-null  int64
 18  hashtags         10004 non-null  object
 19  cashtags         10004 non-null  object
 20  link             10004 non-null  object
 21  retweet          10004 non-null  bool
 22  quote_url        804 non-null    object
 23  video            10004 non-null  int64
 24  thumbnail        1200 non-null   object
 25  near             0 non-null      float64
 26  geo              0 non-null      float64
 27  source           0 non-null      float64
 28  user_rt_id       0 non-null      float64
 29  user_rt          0 non-null      float64
 30  retweet_id       0 non-null      float64
 31  reply_to         10004 non-null  object
 32  retweet_date     0 non-null      float64
 33  translate        0 non-null      float64
 34  trans_src        0 non-null      float64
 35  trans_dest       0 non-null      float64
dtypes: bool(1), float64(10), int64(8), object(17)
memory usage: 2.7+ MB

In [10]:
initial_csv.describe()

,id,conversation_id,timezone,user_id,replies_count,retweets_count,likes_count,video,near,geo,source,user_rt_id,user_rt,retweet_id,retweet_date,translate,trans_src,trans_dest
count,1.000400e+04,1.000400e+04,10004.0,1.000400e+04,10004.000000,10004.000000,10004.000000,10004.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,1.499252e+18,1.498653e+18,0.0,7.203388e+17,0.286385,0.329768,1.332167,0.119952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.324094e+12,1.204184e+16,0.0,6.369849e+17,1.948515,3.203815,14.864489,0.324922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.499248e+18,8.224459e+17,0.0,3.840000e+03,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.499250e+18,1.499146e+18,0.0,5.857509e+08,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.499252e+18,1.499248e+18,0.0,9.049159e+17,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.499254e+18,1.499252e+18,0.0,1.354510e+18,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.499256e+18,1.499256e+18,0.0,1.499253e+18,135.000000,201.000000,1152.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
initial_clean = initial_csv.drop_duplicates()
initial_clean.reset_index(drop=True,inplace=True)

initial_clean['retweet'] = 0

columns = {'index':'tweet','tweet':'count'}
tweet_count = initial_clean['tweet'].value_counts()
tweet_count = tweet_count.to_frame().reset_index().rename(columns=columns)

In [16]:
# for i in initial_csv:
#     tweet = initial_clean.at[i,'tweet']
#     count = tweet_count.loc[tweet_count['tweet'] == tweet]
#     if len(count) > 0:
#         count = count.reset_index(drop=True)['count'][0]
#         initial_clean.at[i,'repost_count'] = count -1